# Generated by Django 2.1.15 on 2022-06-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lessons',
            field=models.ManyToManyField(related_name='Book_Lesson', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='grade',
            name='books',
            field=models.ManyToManyField(related_name='Grade_Book', to='core.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book_Grade', to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson_Book', to='core.Book'),
        ),
    ]
