# Generated by Django 2.1.15 on 2022-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220603_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='books',
        ),
    ]
