# Generated by Django 2.1.15 on 2022-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220603_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='lessons',
            field=models.ManyToManyField(related_name='book', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='grade',
            name='books',
            field=models.ManyToManyField(related_name='grade', to='core.Book'),
        ),
    ]
